### ISSUE TITLE
Feature request: Provide a glob for selecting relevant css files

### ISSUE THREAD

**Issue by yannickzipf** [mauriciolauffer/ui5-task-minifier#4]
Hello Maurico, 
thanks for this great task!
I experienced one problem when working with nesting in css files. The task seems to abort the minification, if there are css files with nested code.

Example for nested code:
```
body {
   h1 {
      text-align: center;
   }
}
```

The folder structure looks like this:
```
- style.css
- src (dir)
--- body.css
--- header.css
--- footer.css
```

In a gulp task, I concat all files within the src folder and process the nesting with postcss-nested. The output (unnested, but unminified) is written into the style.css file. This is the only file that I need to be minified for production.
Therefore it would be nice to have something like a glob to select the relevant css files for your task.

Is it possible for you to provide a solution for that?

Thanks again!
Yannick

**Comment by mauriciolauffer** [comment]
@yannickzipf sorry for the ultra-delayed response. Somehow I missed the notification and never saw this issue.

Sure I can add an option for custom globs. But before that, have you tried using `excludes`? It might be enough for your use case.

```yaml
builder:
  resources:
    excludes:
      - "/something/**"
      - "another-folder/**"
  customTasks:
    - name: ui5-task-minifier
      afterTask: minify
```
